### ISSUE TITLE
Infrastructure as Code - ensure infrastructure can be built in DR case

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-platform#1077]
Update all IasC resources, terraform, scripts etc. 

Make it possible to rebuild complete Radix platform in a Disaster recovery scenario.
**Task** are done sequentially and parallel in all environments (dev/playground/prod/c2) 

- [x] https://github.com/equinor/radix-platform/issues/1180
- [x] Split clusters not to have common resource groups
- [x] https://github.com/equinor/radix-platform/issues/1181
- [x] https://github.com/equinor/radix-platform/issues/1182
- [x] https://github.com/equinor/radix-private/issues/205
- [x] https://github.com/equinor/radix-platform/issues/1183
- [x] https://github.com/equinor/radix-platform/issues/1184
- [x] https://github.com/equinor/radix-platform/issues/1185
- [x] https://github.com/equinor/radix-platform/issues/1188
- [x] https://github.com/equinor/radix-platform/issues/1189
