### ISSUE TITLE
Implement support for KEDA in Radix

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-platform#1282]
Get some insight from the community on which scalers(features) can be the most important. Implement on scaler first and then scale up in the next iteration.

Update radix-config / radix-operator
Install KEDA in infrastructure

User requests:

- [x] https://github.com/equinor/radix/issues/63
- [x] https://github.com/equinor/radix/issues/54

Involve users: Inge, Ronnie, John Ivar

Keda discussion on Workload Identity:
https://github.com/kedacore/keda/issues/5630#issuecomment-2132236785

## TODO:

- [x] https://github.com/equinor/radix-flux/pull/2078
- [x] https://github.com/equinor/radix-flux/pull/2081
- [x] https://github.com/equinor/radix-api/pull/625
  - [x] Release API
- [x] https://github.com/equinor/radix-operator/pull/1116
  - [x] Tag and Release Operator
- [x] https://github.com/equinor/radix-operator/pull/1112
- [x] https://github.com/equinor/radix-api/pull/629
- [x] https://github.com/equinor/radix-api/pull/633
    - [x] Return all triggers, current metric, target metric, errors (invalid spec/missing auth etc)
- [x] https://github.com/equinor/radix-web-console/pull/1040
    - [x] Show trigger/scaling status
    - [x] Show more relevant information when scaled to 0
- [x] https://github.com/equinor/radix-public-site/pull/356
- [x] https://github.com/equinor/radix-flux/pull/2152
- [x] Announce
---
- [ ] Upgrade CRD to allow secrets for auth
- [ ] Upgrade Radix API to set secrets
- [ ] Upgrade Radix CLI to set secrets
- [ ] Write documentation

## Triggers:
- https://keda.sh/docs/2.14/scalers/azure-service-bus/
- https://keda.sh/docs/2.14/scalers/cron/
- https://keda.sh/docs/2.14/scalers/cpu/
- https://keda.sh/docs/2.14/scalers/memory/

DoD
A scaler can be configured and the applicable Pods are scaled using the rules. Information provided in web-console: which scaler, status etc.
