### ISSUE TITLE
Key Vault secrets should have an expiration date

### ISSUE THREAD

**Issue by sondresjolyst** [equinor/radix-platform#922]
### Tasks
- [ ] [radix-vault-dev](https://portal.azure.com/#)
    - [ ] kubernetes-api-server-whitelist-ips-dev
- [ ] [radix-sci-az-kv-test](https://portal.azure.com/#)
    - [ ] secret2
    - [ ] another-secret
    - [ ] a-secret-from-keyvault
- [ ] [radix-app-secrets2](https://portal.azure.com/#)
    - [ ] db-user
    - [ ] db-qa-user
    - [ ] db-password
    - [ ] connection-string-test
    - [ ] connection-string-prod
- [ ] [kv-radix-monitoring-dev](https://portal.azure.com/#)
    - [ ] s941-radix-grafana-dev-mysql-admin-pwd
    - [ ] s941-radix-grafana-playground-mysql-admin-pwd
    - [ ] mysql-radix-grafana-dev-ip

### Problem:
Key Vault secrets should have an expiration date

### Possible solution:
[check_keyvault_secrets.sh](https://github.com/equinor/radix-platform/blob/master/scripts/check_keyvault_secrets.sh)

Instead of checking `AZ_RESOURCE_KEYVAULT` we could create a function that loops through `az keyvault list` and check every keyvault in current subscription.
